### ISSUE TITLE
Any way of using this with Sandbox Apps?

### ISSUE THREAD

**Issue by AlexPerathoner** [emorydunn/LaunchAgent#2]
I have been trying for a while to find a way of loading an Agent with Sandbox capability enabled, but without success.
Am I doing something wrong or, as the Package is trying to write to the user's library, isn't there any way to do this at all?

**Comment by emorydunn** [comment]
Unfortunately you'll need the user's help in order to access LaunchAgents. You can use an `NSSavePanel` or `NSOpenPanel` to get permission to access the plist, which would allow you to update it. 

```swift
let agent = LaunchAgent(label: "SavePanelAgent", program: ["echo", "SavePanelAgent"])

let savePanel = NSSavePanel()
savePanel.nameFieldStringValue = "SavePanelAgent"
savePanel.allowedFileTypes = ["plist"]

let response = savePanel.runModal()

switch response {
case .OK:
    print(savePanel.url!)
    
    do {
        try LaunchControl.shared.write(agent, to: savePanel.url!)
        
        try LaunchControl.shared.load(agent)
    } catch {
        self.presentError(error)
    }

default:
    break
}
```

**Comment by AlexPerathoner** [comment]
Perfect! That's exactly what I was looking for. As soon as I have time I'll try it out. Thanks!
