### ISSUE TITLE
Unexpected error: urlNotSet

### ISSUE THREAD

**Issue by theRealGupta** [emorydunn/LaunchAgent#3]
Hi @emorydunn 
I tried to use your LaunchAgent I created the framework, After that, I import in my project it looks fine.
But when I am trying to load that time I am getting Exception.

`Unexpected error: urlNotSet(label: "com.local.test")`

```
  let test = LaunchAgent(label: "com.local.test", program: ["bash","-c","my program"])
        test.runAtLoad = true;
        test.keepAlive = true;
          
        print("test",test.label);
        
        do {
            try test.load();
        } catch {
            print("Unexpected error: \(error).")
        }
        test.start();
```

![Screenshot 2020-08-31 at 9 22 39 PM](https://user-images.githubusercontent.com/6472263/91747259-7ca86f80-ebdb-11ea-8bff-551be79937c0.png)

**Comment by anupgupta-arg** [comment]
![Screenshot 2020-08-31 at 9 22 39 PM](https://user-images.githubusercontent.com/6472263/91747259-7ca86f80-ebdb-11ea-8bff-551be79937c0.png)

**Comment by emorydunn** [comment]
Is your app running in a sandbox? If so LaunchAgent can't get the real URL for the plist.

**Comment by theRealGupta** [comment]
@emorydunn so how I can use this?

**Comment by emorydunn** [comment]
The only way to access files outside of your app's sandbox is to ask the user for permission. You can take a look at #2 for more info.

**Comment by theRealGupta** [comment]
@emorydunn based on #2 no Url Issue but while Starting Again **Not privileged to start service.**
```
2020-09-01 09:35:31.732665+0530 launchctl[8133:4350618] [All] launchctl start: /bin/launchctl start SavePanelAgent
Not privileged to start service.
```

Should I provide any thing extra privileged?

**Comment by emorydunn** [comment]
Can you start the agent from `launchctl` directly? You might try using [LaunchControl](https://www.soma-zone.com/LaunchControl/) as another means of inspecting the agent.

**Comment by theRealGupta** [comment]
@emorydunn 
I am able to load and start from the terminal.

<img width="655" alt="Screenshot 2020-09-01 at 10 26 10 AM" src="https://user-images.githubusercontent.com/6472263/91796368-9a0e2580-ec3d-11ea-8c10-3eaa476026ae.png">

**Comment by emorydunn** [comment]
I think there might be a couple of issues. I missed this in your code sample, but if you're creating an agent for the first time it needs to be written to disk first. This isn't really documented anywhere, so I'll fix that. 

```swift
let agent = LaunchAgent(label: "TestAgent", program: "date")

do {
    try LaunchControl.shared.write(agent)
    try agent.load()
} catch {
    print("Unexpected error: \(error).")
}
```

The next is your agent plist is located in the global agents folder (`/Library/LaunchAgents`), rather than the user agents folder. The framework only looks for agents in the user space. 

Try either writing the agent to disk or moving the file to the `~/Library/LaunchAgents` and let me know if it works.

**Comment by theRealGupta** [comment]
@emorydunn Yes, You are right I also did the same thing It's working like a charm. And I also disable the app sandbox.
